# Generated by Django 3.2.9 on 2021-11-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('telephone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('car', models.CharField(max_length=40, verbose_name='Автомобиль')),
                ('data', models.DateField(verbose_name='Дата осмотра')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30, verbose_name='Модель автомобиля')),
                ('register_sign', models.CharField(max_length=8, verbose_name='Регистационный номер')),
                ('car_color', models.CharField(max_length=40, verbose_name='Цвет автомобиля')),
                ('year_issue', models.IntegerField(max_length=4, verbose_name='Год выпуска')),
                ('engine_number', models.CharField(max_length=14, verbose_name='Номер двигателя')),
                ('body_number', models.CharField(max_length=12, verbose_name='Номер кузова')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('mileage', models.IntegerField(max_length=6, verbose_name='Пробег')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('telephone', models.CharField(max_length=11, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='TypesJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=40, verbose_name='Наименование')),
                ('cost_work', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стиомость работы')),
                ('lead_time', models.IntegerField(max_length=4, verbose_name='Время выполнения')),
                ('guarantee', models.CharField(max_length=200, verbose_name='Гарантия')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('name_lastname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('telephone', models.CharField(max_length=11, verbose_name='Телефон')),
                ('e_mail', models.EmailField(max_length=50, verbose_name='Почта')),
                ('position', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='car.position', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appeal', models.DateField(verbose_name='Дата начала')),
                ('date_completion', models.DateField(verbose_name='Дата окончания')),
                ('reason_petition', models.CharField(max_length=1000, verbose_name='Причина обращения')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая стоимость')),
                ('order_status', models.CharField(max_length=20, verbose_name='Статус')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.appointment', verbose_name='Обращение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Автомобиль')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.user', verbose_name='Мастер')),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('remainder', models.IntegerField(max_length=3, verbose_name='Отстаток')),
                ('spare_cost', models.IntegerField(max_length=7, verbose_name='Стоимость')),
                ('guarantee', models.CharField(max_length=200, verbose_name='Гарантия')),
                ('suppliers', models.ManyToManyField(to='car.Supplier')),
            ],
            options={
                'verbose_name': 'Spare',
                'verbose_name_plural': 'Spares',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=40, verbose_name='Наименование')),
                ('number_spare_parts', models.IntegerField(max_length=4, verbose_name='Количество запасных частей')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.typesjob', verbose_name='Тип работы')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.spare', verbose_name='Запчасти')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.user', verbose_name='Владелец'),
        ),
    ]
