# Generated by Django 3.2.9 on 2021-11-07 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('telephone', models.CharField(max_length=11)),
                ('car', models.CharField(max_length=40)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=30)),
                ('register_sign', models.CharField(max_length=8)),
                ('car_color', models.CharField(max_length=40)),
                ('year_issue', models.IntegerField(max_length=4)),
                ('engine_number', models.CharField(max_length=14)),
                ('body_number', models.CharField(max_length=12)),
                ('vin', models.CharField(max_length=17)),
                ('mileage', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('remainder', models.IntegerField(max_length=3)),
                ('spare_cost', models.IntegerField(max_length=7)),
                ('guarantee', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(max_length=2)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.position')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TypesJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=40)),
                ('cost_work', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lead_time', models.IntegerField(max_length=4)),
                ('guarantee', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('e_mail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appeal', models.DateField()),
                ('date_completion', models.DateField()),
                ('reason_petition', models.CharField(max_length=1000)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_status', models.CharField(max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.appointment')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.user'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=40)),
                ('number_spare_parts', models.IntegerField(max_length=4)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.typesjob')),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.spare')),
            ],
        ),
        migrations.CreateModel(
            name='PartsSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_spare_parts', models.IntegerField(max_length=3)),
                ('guarantee', models.CharField(max_length=200)),
                ('spares', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.spare')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.user'),
        ),
    ]
