# Generated by Django 3.2.7 on 2021-10-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='partssupplier',
            old_name='spares_id',
            new_name='spares',
        ),
        migrations.RenameField(
            model_name='partssupplier',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='spare_id',
            new_name='spare',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='work_order_id',
            new_name='work_order',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='position_id',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='appointment_id',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='stuff_id',
            new_name='stuff',
        ),
    ]
