# Generated by Django 3.2.9 on 2021-11-17 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20211117_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spare',
            options={'verbose_name': 'Spare', 'verbose_name_plural': 'Spares'},
        ),
        migrations.AddField(
            model_name='spare',
            name='suppliers',
            field=models.ManyToManyField(to='car.Supplier'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car',
            field=models.CharField(max_length=40, verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='data',
            field=models.DateField(verbose_name='Дата обращения/ремонта'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_number',
            field=models.CharField(max_length=12, verbose_name='Номер кузова'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_color',
            field=models.CharField(max_length=40, verbose_name='Цвет автомобиля'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_number',
            field=models.CharField(max_length=14, verbose_name='Номер двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(max_length=6, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='register_sign',
            field=models.CharField(max_length=8, verbose_name='Регистационный номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.user', verbose_name='Номер пользователя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_issue',
            field=models.IntegerField(max_length=4, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='position',
            name='job_title',
            field=models.CharField(max_length=50, verbose_name='Нименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.typesjob', verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_service',
            field=models.CharField(max_length=40, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='number_spare_parts',
            field=models.IntegerField(max_length=4, verbose_name='Количество запасных частей'),
        ),
        migrations.AlterField(
            model_name='service',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.spare', verbose_name='Запчасти'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='guarantee',
            field=models.CharField(max_length=200, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='remainder',
            field=models.IntegerField(max_length=3, verbose_name='Отстаток'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='spare_cost',
            field=models.IntegerField(max_length=7, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.IntegerField(max_length=2, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.user', verbose_name='Номер пользователя'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='telephone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='typesjob',
            name='cost_work',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стиомость работы'),
        ),
        migrations.AlterField(
            model_name='typesjob',
            name='guarantee',
            field=models.CharField(max_length=200, verbose_name='Гарантия'),
        ),
        migrations.AlterField(
            model_name='typesjob',
            name='lead_time',
            field=models.IntegerField(max_length=4, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='typesjob',
            name='name_work',
            field=models.CharField(max_length=40, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.appointment', verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date_appeal',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date_completion',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_status',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='reason_petition',
            field=models.CharField(max_length=1000, verbose_name='Причина обращения'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.staff', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Общая стоимость'),
        ),
        migrations.DeleteModel(
            name='PartsSupplier',
        ),
    ]
