# Generated by Django 3.2.9 on 2021-11-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20211127_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spare',
            old_name='supplier',
            new_name='suppliers',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='service',
            new_name='services',
        ),
    ]
