# Generated by Django 3.2.7 on 2021-10-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20211024_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='work_order',
        ),
    ]
