# Generated by Django 3.2.7 on 2021-10-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_service_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=50)),
                ('experience', models.IntegerField(max_length=2)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.user')),
            ],
        ),
    ]
