# Generated by Django 3.2.9 on 2021-12-22 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20211127_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Рег. номер авто'),
        ),
        migrations.AlterField(
            model_name='service',
            name='number_spare_parts',
            field=models.IntegerField(max_length=4, verbose_name='Кол. запасных частей'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='services',
            field=models.ManyToManyField(to='car.Service', verbose_name='Услуги'),
        ),
    ]
