# Generated by Django 3.2.9 on 2021-12-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_appointment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Рег. номер авто'),
        ),
    ]
